# Generated by Django 2.1.2 on 2018-12-12 01:09

import book.models
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anthology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', mdeditor.fields.MDTextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('click_number', models.IntegerField(default=0)),
                ('publish', models.BooleanField(default=False)),
                ('anthology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Anthology')),
            ],
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('introduce', models.CharField(max_length=255, blank=True, null=True)),
                ('head', models.ImageField(default='http://img3.duitang.com/uploads/item/201505/22/20150522205616_KeX3C.jpeg', upload_to=book.models.image_upload_to)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Users'),
        ),
        migrations.AddField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='book.Comments'),
        ),
        migrations.AddField(
            model_name='collect',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Users'),
        ),
        migrations.AddField(
            model_name='attention',
            name='ByFollowers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='book.Users'),
        ),
        migrations.AddField(
            model_name='attention',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='book.Users'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Users'),
        ),
        migrations.AddField(
            model_name='anthology',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Users'),
        ),
    ]
